apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-001
  labels:
    type: local
spec:
  storageClassName: pv-hostpath
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"  
  
