apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-001
  labels:
    type: local
spec:
  storageClassName: pv-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
